### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/expunge.io#1]
Create a page at http://expunge.io/privacy and add a link to it in the footer of the site.

Here's text: 

Privacy Policy
 
Introduction 
Expunge.io values your online privacy and is committed to safe guarding the data you share with us and your online privacy. Our On-Line Privacy Policy applies to data collected at the expunge.io domain.

Information we collect 
Expunge.io only collects information you share with the application regarding contact information related to eligibility to apply for juvenile expungement in Illinois. We collect this data using a form located at http://www.expunge.io/eligible1, http://www.expunge.io/eligible2, and http://www.expunge.io/eligible3.
 
We do not collect personal information without your permission. Any information that you volunteer or that we send to you in response is transferred using industry standard encryption technologies. We use the service provided at http://www.wufoo.com.
 
Expunge.io collects your name and email address so that a representative from the Juvenile Expungement Help Desk may contact you regarding your report. Expunge.io also collects your phone number and how you heard about expunge.io.
 
We do not use or set cookies on our website to store any information on your personal computer hard drive.
 
Data we share 
Expunge.io will share the necessary data you entered and store only what you provided required to submit your information to representatives from the Juvenile Expungement Help Desk. This data may be shared with another legal assistance agency that can help you with expungement. All other information is deleted from your cache memory when you close the session and leave our site. We collect no other personal information.
 
Expunge.io does not sell or share your data with any 3rd parties.

Other Websites 
This site contains links to other sites. We are not responsible for the privacy practices or the content of all the sites listed.

Contact 
We value your feedback. If you would like your data removed from the system, or have questions regarding the application, contact Sharlyn Grace, VISTA Attorney, LAF, Children and Families Practice Groups, at SGrace@LAFChicago.org.

**Comment by danxoneil** [comment]
From Vivian Hessel:

Thanks to all for your feedback. I think we are ready to post these documents on www.expunge.io but please shout out if you have any comments or concerns.

The revised Privacy Policy is here:  
https://docs.google.com/document/d/179z37FM1J0KZhzotId-osWRkDUkfcKOa4UGBw5JzN2c/edit
 
The revised Terms of Use is here:
https://docs.google.com/document/d/1q3UKGq7LrHz7EPF5AnvKG4Ox34KYzDb_EUn1DQzmtRs/edit

**Comment by cathydeng** [comment]
added!

http://www.expunge.io/about
http://www.expunge.io/disclaimer
