### ISSUE TITLE
Duplicate keys in es.yml file

### ISSUE THREAD

**Issue by cameron-r** [smartchicago/expunge.io#13]
on lines 272 and 279 of config/locales/views/questions/es.yaml there is a definition for juvenile_expungement_help_desk. This will create some unexpected behaviour when the pages are rendered. The 2nd instance of 'juvenile_expungement_help_desk' should either get a new name, or should be removed

**Comment by cathydeng** [comment]
no longer relevant since spanish version is now a separate static site, closing
