### ISSUE TITLE
Eligibility question flow is different in English and Spanish

### ISSUE THREAD

**Issue by wlbehr** [smartchicago/expunge.io#15]
There are significant differences between the flow of eligibility questions in the English and Spanish versions of pages. 

This is important because expunge.io visitors who speak Spanish may have a different experience (and different result to the questionnaire) than visitors who speak English.

We need to verify the correct flow of questions for eligibility before we can make further progress on streamlining the way translations are handled.

English Eligibility Flow:

![expungeio_en_eligibility_flow](https://cloud.githubusercontent.com/assets/8498270/5531943/f99c7588-89f6-11e4-835b-6230a8a45ad1.jpg)

Spanish Eligibility Flow:

![expungeio_es_eligibility_flow](https://cloud.githubusercontent.com/assets/8498270/5531946/fedad2ba-89f6-11e4-9e6d-939c9bb25b31.jpg)

**Comment by cathydeng** [comment]
fixed
