### ISSUE TITLE
Add new information about obtaining rap sheets at Cook County Juvenile Center

### ISSUE THREAD

**Issue by smarziano** [smartchicago/expunge.io#16]
Based on the new process of the fingerprint terminal and ICLEAR system being accessible at the Cook County Juvenile Center, we need to update this page: http://www.expunge.io/step2

Cook County Juvenile Center
1100 S. Hamilton Ave, Chicago, IL  60612

I am currently verifying the best phone #, hours, and any additional instructions that might be useful.

As reference, here is a link re: the fingerprint terminal at Cook County Juvenile Center: http://www.smartchicagocollaborative.org/fingerprint-terminal-at-cook-county-juvenile-center/

**Comment by cathydeng** [comment]
!!!

this is awesome.

what's the relationship between the iclear system & the fingerprint terminal? is the iclear system the same as what LAF currently uses to look up arrest records in cook county, w/ a client's verbal permission?

how does the fingerprint terminal work? does it just look up and provide RAP sheets, given a fingerprint? is it the exact same RAP sheet as the police dept would provide? when would someone use the fingerprint terminal over iclear - is the terminal primarily for arrests outside chicago & older arrests?

also, does the RAP sheet release form mean that someone w/ a juvenile record only needs to provide a fingerprint, & then LAF will take care of the expungement application? if so, that'd be amazing.

**Comment by smarziano** [comment]
It _is_ pretty awesome, and we're still working through some logistics (such as hours and release form) since this is a new process and deeper collaboration between the Help Desk and Probation Services.

The ICLEAR system and fingerprint terminal are separate systems that both have their pros and limitations. I described them in the above blog post. The fingerprint terminal is a scanner that captures fingerprint images that is used to look up and provide the rap sheet. If the release form is filled out, the rap sheet is delivered to the Help Desk attorneys and the lawyers will be able to complete and file the petition paperwork on behalf of their client. The terminal is especially useful for any rap sheets that cannot be found in ICLEAR, mainly arrests outside of Chicago, and older arrests that might not be in the ICLEAR system.

The ICLEAR system is a name-based search that can look up rap sheets for arrests within Chicago.

The best part of these systems is that if someone goes to the Help Desk before getting their rap sheet, they can easily go get it or start the process, and can complete everything in one place.

**Comment by smarziano** [comment]
If you were arrested in *or* outside of Chicago, you can pickup your arrest record for free in person at:
Juvenile Expungement Help Desk at Cook County Juvenile Center
1100 S Hamilton Ave, Chicago, IL 60612
(312) 229-6359
Monday - Tuesday: 9:00 AM - 4:00 PM, Thursday: 9:00 AM - 12:00 PM

@cathydeng - You can keep the other information on this page as alternative options to get rap sheets, but this is the key way to get a rap sheet. We want to drive people to get their rap sheet and free legal advice from the lawyers at the Help Desk.
