### ISSUE TITLE
'call the help desk' -> 'call camille'

### ISSUE THREAD

**Issue by cathydeng** [smartchicago/expunge.io#18]
b/c 'help desk' has negative annotations - expectation of hold music, apathetic person on the other end

**Comment by smarziano** [comment]
@cathydeng -- here is a photo of Camille that she has allowed us to use for Expunge.io. It could be even better to add a face to the Juvenile Expungement Help Desk!
![image001](https://cloud.githubusercontent.com/assets/5550969/8274399/f0948720-1856-11e5-8dd9-3ec6935231ba.jpg)

**Comment by cathydeng** [comment]
perfect! I was tryna google for a LAF headshot earlier today :)
