### ISSUE TITLE
Buttons disappear in Spanish version

### ISSUE THREAD

**Issue by smarziano** [smartchicago/expunge.io#26]
When switching Expunge.io into Spanish, the buttons disappear. This causes an issue when the user hovers over the text because the text becomes white and it can't be seen on the background. Here is an example:

<img width="1238" alt="screen shot 2015-09-11 at 4 52 45 pm" src="https://cloud.githubusercontent.com/assets/5550969/9827221/b206e0cc-58a5-11e5-8f75-0d987532eff7.png">

**Comment by cathydeng** [comment]
fixed
