### ISSUE TITLE
Add more information on current disclaimer page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/expunge.io#36]
This relates to issue #35. 

Viewing some Google Analytics from September 1 - January 11, 41% of users who visited Expunge.io clicked on the "Find out if you're eligible" button on the homepage. However, only 12% of those people got past the disclaimer and 18% clicked "Home." We have an opportunity to provide more information about expungement and then context about the disclaimer to drive people to continue.

Add additional information to this page: http://www.expunge.io/disclaimer

Here is an example wireframe of that page:
![over_18_ disclaimer 4](https://cloud.githubusercontent.com/assets/5550969/12336579/dcd99362-baca-11e5-9f78-5d175790c256.png)

**Comment by cathydeng** [comment]
instead of adding more text to the disclaimer page, I'll nix the disclaimer page and add a note to the homepage, so that it's not n extra page people have to click through
